# Generated by Django 2.0.7 on 2020-03-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='league',
            field=models.CharField(choices=[('PL', 'Premier League'), ('LL', 'La liga'), ('SA', 'Seria A'), ('L1', 'League 1'), ('CL', 'Champions league'), ('BL', 'Bundas league')], default='PL', max_length=32),
        ),
    ]
